import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-950 text-neutral-200 selection:bg-cyan-500/30`}
      >
        <Navbar />
        {children}
        {/* Footer */}
        <footer className="py-8 border-t border-white/5 text-center text-sm text-neutral-500">
          <p>&copy; {new Date().getFullYear()} Mon Portfolio. Fait avec Next.js & Tailwind.</p>
        </footer>
      </body>
    </html>
  );
}
